### ISSUE TITLE
Revisit the utility of waiting for (some) actions when scaling instances up or down

### ISSUE THREAD

**Issue by djcp** [harvard-dce/ec2-management#13]
There are probably times when we want / need to wait - to ensure maintenance mode is enabled, etc, but generally if we're shutting down an instance we're probably OK just turning on maintenance mode, sending the shutdown API call and moving on.

**Comment by spiraleddy** [comment]
If the instance is not actively working on a task, or waiting for child tasks to complete, setting it to maintenance just ensures it doesn't pick up a new task will you're trying to shut it down. So I agree.
